import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/custom/Footer";
import { cn, getGlobalData } from "@/lib/utils";
import { Header } from "@/components/custom/Header";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getGlobalData();

  return (
    <html lang="en">
      <body className={cn("min-h-screen", inter.className)}>
        <Header data={globalData.header} />
        {children}
        <Toaster />
        <Footer data={globalData.footer} />
      </body>
    </html>
  );
}
